version: "3.9"
services:
  backend:
    build: .
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://chat_user:StrongPassword123@db:5432/chat_app
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: StrongPassword123
      POSTGRES_DB: chat_app
    ports:
      - "5432:5432"
